# Generated by Django 3.2.4 on 2021-06-23 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 23, 12, 11, 55, 845110, tzinfo=utc)),
        ),
    ]
