# Generated by Django 3.2.4 on 2021-06-27 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 27, 5, 22, 20, 380878, tzinfo=utc)),
        ),
    ]
